spring:
  profiles:
    active: dev

---
spring:
  application:
    name: config-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: config-test
  config:
    activate:
      on-profile: test