spring:
  profiles:
    active: dev

---
server:
  port: 8201

spring:
  application:
    name: provider
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

---
server:
  port: 8202

spring:
  application:
    name: provider
  config:
    activate:
      on-profile: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka